version: "3.9"

services:
  mysql:
    image: mysql:8.0
    container_name: terretashop_mysql
    restart: unless-stopped

    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: terretashop_db
      MYSQL_USER: terretashop_user
      MYSQL_PASSWORD: terretashop_pass

    ports:
      - "3306:3306"

    volumes:
      - mysql_data:/var/lib/mysql
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql:ro

    command: >
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_unicode_ci

volumes:
  mysql_data:
