services:
  traefik:
    image: traefik:v3.3
    container_name: traefik
    restart: unless-stopped
    command:
      - --log.level=${TRAEFIK_LOG_LEVEL}

      # Providers
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --providers.docker.network=traefik-public
      - --providers.file.filename=/etc/traefik/dynamic.yml
      - --providers.file.watch=true

      # EntryPoints
      - --entrypoints.web.address=:80
      - --entrypoints.websecure.address=:443

      # RedirecciÃ³n HTTP -> HTTPS
      - --entrypoints.web.http.redirections.entryPoint.to=websecure
      - --entrypoints.web.http.redirections.entryPoint.scheme=https

      # Dashboard (sin exponer 8080; se publica por router interno)
      - --api.dashboard=true

      # Let's Encrypt (HTTP-01)
      - --certificatesresolvers.letsencrypt.acme.email=${LE_EMAIL}
      - --certificatesresolvers.letsencrypt.acme.storage=/letsencrypt/acme.json
      - --certificatesresolvers.letsencrypt.acme.httpchallenge.entrypoint=web
      # Compatibilidad: forzamos certificado RSA (evita problemas de confianza en algunos clientes/redes con ECDSA)
      - --certificatesresolvers.letsencrypt.acme.keytype=RSA2048
    ports:
      - 80:80
      - 443:443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - traefik_letsencrypt:/letsencrypt
      - ./traefik/dynamic.yml:/etc/traefik/dynamic.yml:ro
      - ./traefik/users.htpasswd:/etc/traefik/users.htpasswd:ro
    networks:
      - traefik-public

volumes:
  traefik_letsencrypt:

networks:
  traefik-public:
    external: true
